baseline: &baseline

  target_features:
    - OSTM
    - RFSTM
    - EFSTM
    - CR1_Y
    - CR1_N

  
  drop:
    - ELNRisk



  target_dimensionalities:
    - 2
    - 3
    - 4
    - 5

  transformation:
    PrincipalComponentAnalysis:
    IncrementalPrincipalComponentAnalysis:
    SparsePrincipalComponentAnalysis:
    SingularValueDecomposition:
    GaussianRandomProjection:
    SparseRandomProjection:
    MultiDimensionalScaling:
    ISOMAP:
    LinearLocalEmbedding:
    Mini-BatchDictionaryLearning:
    AutoEncoder:

 
  min_number_of_clusters: 2

  max_number_of_clusters: 8
 
  min_rel_cluster_size: 0.05

    target_number_of_clusters:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8

   clustering:
    k-Means:
    TwoMeans:
    AgglomerativeClustering:
    SpectralClustering:
    Linkage:
    BIRCH:
    GaussianMixture:
    OPTICS:
    MeanShift:
    DBSCAN:
    AffinityPropagation:

  
 
  max_number_of_results: 605

  visualization_min_single_cluster_diff: 0.1

  export_detailed_cluster_assignments: true

  random_seed: 42
 
  runs_per_config: 10
 